// GENERATED by brand/tools/generate-icons.mjs — do not edit by hand.
//
// The Mioryde mark as one silhouette, for drawing inline where the shape has to
// take its colour from the theme rather than from an asset. Regenerate with
// `node brand/tools/generate-icons.mjs`.

/** Tight around the artwork, so the mark fills whatever box it is given. */
export const BRAND_MARK_VIEWBOX = "93 104 326 326";

/** The teardrop, with the counter as an `evenOdd` hole. */
export const BRAND_MARK_PIN =
  "M256 104 C 178 104 115 167 115 245 C 115 318 196 380 256 430 C 316 380 397 318 397 245 C 397 167 334 104 256 104 Z M266 145 a 90 90 0 1 1 0 180 a 90 90 0 1 1 0 -180 Z";

/** The road through the counter. */
export const BRAND_MARK_ROAD =
  "M343 202 C 310 205 274 212 242 222 C 214 233 196 245 186 260 C 186 295 205 335 236 358 C 252 348 262 332 258 306 C 250 290 253 268 264 252 C 284 230 312 212 343 202 Z";
